### ISSUE TITLE
Add an option to change permissions of all commands

### ISSUE THREAD

**Issue by SpLeNd1d222** [imDMK/SpentTime#10]
What are the commands and permissions? Can't find anywhere about them

**Comment by imDMK** [comment]
Hello, here you can find command permissions.
![image](https://github.com/imDMK/SpentTime/assets/81445555/e7cd6152-0e58-43fd-a11f-6b4ad82c83a8)
If you have additional questions, ask!
Regards.

**Comment by imDMK** [comment]
Let me know if you solved the problem.

**Comment by SpLeNd1d222** [comment]
But these two are only for resetting the time. Is the permission to use this plugin available by default for all player groups? What node should I use if I want to disable /spenttime command for a specific group?

**Comment by imDMK** [comment]
Okay, I understand you. 

Unfortunately, I did not introduce such an option.
But I promise that I will add this function soon and if you really need it, I can send you a plugin with this function.

Thank you for your feedback - Your opinion is correct.

**Comment by SpLeNd1d222** [comment]
Okay, thank you! Will look forward with such changes:)

**Comment by imDMK** [comment]
I reopened this issue because it will close automatically when I implement your suggestion. By the way, you will receive a notification when your suggestion will be completed.

**Comment by SpLeNd1d222** [comment]
Ah okay, I was wondering if I should close it or not xd Cool, thanks!

**Comment by imDMK** [comment]
After thinking about it, I introduced a different system. 
Now permissions are not configurable. More information at #11.
Let me know what you think here #11.

**Comment by imDMK** [comment]
Hello, Before I merge changes at #11 I'm waiting for your opinion! 😎
